[package]
name = "paraxis"
authors = ["Glenn Wallace glennw-coding@proton.me"]
description = "A maths library for doing calculations on spatial data."
version = "0.1.5"
edition = "2024"
keywords = ["maths", "gpu", "vectorization", "linear-algebra", "numpy"]
categories = ["mathematics"]
license = "MIT"
repository = "https://github.com/glennw-mt/paraxis"

[dependencies]
dashmap = { version = "6.1.0", features = ["rayon"] }
rayon = "1.11.0"
